'use client';
import React,{useState,useEffect,useRef} from 'react';
import {Activity,ArrowDownToLine,ArrowLeft,ArrowRight,ArrowUpRight,BarChart3,Bell,Bookmark,Check,ChevronDown,ChevronRight,CircleHelp,Clapperboard,Clock,Download,Expand,Flag,LayoutDashboard,Layers,ListFilter,MessageSquare,MoreHorizontal,Pause,Play,Plus,Search,Send,Settings,Shield,SkipBack,SkipForward,SlidersHorizontal,Sparkles,Target,Trash2,Upload,Users,Video,X} from 'lucide-react';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Sidebar,SidebarProvider,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger} from '@/components/ui/sidebar';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Progress} from '@/components/ui/progress';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {Toaster,toast} from 'sonner';
import {events,players,matches,stamp,stages} from '@/lib/demo';
import {uploadVideo,uploadRequest,type UploadSession} from '@/lib/upload-client';
type Rec={id:string,kind:string,data:any};
function Choice({value,onChange,options}:{value:string,onChange:(v:string)=>void,options:string[]}){return <Select value={value} onValueChange={onChange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{options.map(v=><SelectItem value={v} key={v}>{v}</SelectItem>)}</SelectContent></Select>}
function Pitch({time=0,shape=true,labels=true,heat=false,selected=0,onSelect=()=>{},grid=false}:{time?:number,shape?:boolean,labels?:boolean,heat?:boolean,selected?:number,onSelect?:(n:number)=>void,grid?:boolean}){const pos=[[8,50],[25,17],[22,39],[22,65],[25,85],[46,28],[39,51],[48,73],[70,18],[76,50],[69,82]];return <svg className="pitch" viewBox="0 0 1000 620" role="img" aria-label="Interactive simulated soccer player positions"><defs><pattern id="grass" width="125" height="620" patternUnits="userSpaceOnUse"><rect width="125" height="620" fill="#254537"/><rect width="62.5" height="620" fill="#284b3b"/></pattern><radialGradient id="heat"><stop stopColor="#d6ec7d" stopOpacity=".7"/><stop offset="1" stopColor="#bedf70" stopOpacity="0"/></radialGradient></defs><rect width="1000" height="620" fill="#1b3228"/><rect x="45" y="40" width="910" height="540" fill="url(#grass)"/><g fill="none" stroke="#b4c7ac" strokeWidth="1.7" opacity=".6"><rect x="45" y="40" width="910" height="540"/><path d="M500 40V580M45 175H190V445H45M955 175H810V445H955M45 248H98V372H45M955 248H902V372H955"/><circle cx="500" cy="310" r="75"/><path d="M190 248Q235 310 190 372M810 248Q765 310 810 372"/><rect x="29" y="280" width="16" height="60"/><rect x="955" y="280" width="16" height="60"/></g>{grid&&<g stroke="#d8e7d7" opacity=".2" strokeDasharray="5 6">{[227,409,591,773].map(x=><path key={x} d={`M${x} 40V580`}/>)}{[220,400].map(y=><path key={y} d={`M45 ${y}H955`}/>)}</g>}{heat&&[380,460,570,640].map((x,i)=><ellipse key={x} cx={x} cy={230+i*60} rx="155" ry="100" fill="url(#heat)"/>)}{shape&&<g fill="#c1ed8330" stroke="#c1ed8390" strokeWidth="2"><path d="M270 132L245 250L245 391L270 499L482 434L700 483L763 310L700 137L464 191Z"/><path d="M464 191L394 315L482 434M270 132L464 191L700 137M245 391L482 434L763 310" fill="none" strokeDasharray="7 6"/></g>}{pos.map(([x,y],i)=>{let px=45+x*9.1+Math.sin(time/18+i)*10,py=40+y*5.4+Math.cos(time/22+i)*8;return <g key={i} onClick={()=>onSelect(i+1)} role="button" tabIndex={0} aria-label={`Select ${players[i].name}`} onKeyDown={e=>e.key==='Enter'&&onSelect(i+1)} style={{cursor:'pointer'}}><circle cx={px} cy={py} r={selected===i+1?23:19} fill="#c7ed89" fillOpacity=".1" stroke="#c7ed89" strokeOpacity=".45"/><circle cx={px} cy={py} r="12" fill="#c7ed89"/>{labels&&<text x={px} y={py+4} textAnchor="middle" fill="#152718" fontSize="12" fontWeight="700">{players[i].number}</text>}</g>})}{pos.map(([x,y],i)=><g key={i}><circle cx={955-x*7.4+Math.cos(time/19+i)*8} cy={48+y*5.2} r="11" fill="#94b5dd"/><circle cx={955-x*7.4+Math.cos(time/19+i)*8} cy={48+y*5.2} r="17" fill="none" stroke="#94b5dd55"/></g>)}<circle cx={530+Math.sin(time/40)*70} cy={325+Math.cos(time/40)*70} r="5" fill="white"/><text x="62" y="603" fontSize="12" fill="#a4b4a3" letterSpacing="2">NORTHSTAR FC →</text><text x="942" y="603" textAnchor="end" fontSize="12" fill="#a4b4a3">SIMULATED TRACKING</text></svg>}
export default function Workspace({initialView='match'}:{initialView?:string}){
const [view,setView]=useState(initialView),[tab,setTab]=useState('Overview'),[time,setTime]=useState(2538),[playing,setPlaying]=useState(false),[speed,setSpeed]=useState('1×'),[shape,setShape]=useState(true),[labels,setLabels]=useState(true),[grid,setGrid]=useState(false),[heat,setHeat]=useState(false),[selected,setSelected]=useState(7),[records,setRecords]=useState<Rec[]>([]),[modal,setModal]=useState(''),[note,setNote]=useState(''),[question,setQuestion]=useState(''),[messages,setMessages]=useState<any[]>([]),[asking,setAsking]=useState(false),[filter,setFilter]=useState('All events'),[search,setSearch]=useState(''),[file,setFile]=useState<File|null>(null),[step,setStep]=useState(0),[uploadProgress,setUploadProgress]=useState(0),[job,setJob]=useState<any>(null),[metadata,setMetadata]=useState({opponent:'',date:new Date().toISOString().slice(0,10),competition:'Regional League',formation:'4-3-3',orientation:'Left to right',consent:false}),[corners,setCorners]=useState<number[][]>([]),[source,setSource]=useState(''),[team,setTeam]=useState('Northstar FC'),[teamDraft,setTeamDraft]=useState(''),[clipStart,setClipStart]=useState('42:08'),[clipEnd,setClipEnd]=useState('42:28'),[loading,setLoading]=useState(false);
const video=useRef<HTMLVideoElement>(null),fileInput=useRef<HTMLInputElement>(null);
const uploadSession=useRef<{file:File;session:UploadSession}|null>(null);
const navigate=(v:string)=>{setView(v);window.history.pushState({},'',v==='match'?'/':'/'+v)};
const openUpload=()=>{setModal('upload');setStep(0)};
// Deep link from the tracking workspace: /dashboard?upload=1 opens the upload dialog once.
useEffect(()=>{const q=new URLSearchParams(window.location.search);if(q.get('upload')!=='1')return;q.delete('upload');const rest=q.toString();window.history.replaceState({},'',window.location.pathname+(rest?'?'+rest:''));const id=setTimeout(openUpload,0);return()=>clearTimeout(id)},[]);
useEffect(()=>{const pop=()=>setView(location.pathname.slice(1)||'match');window.addEventListener('popstate',pop);return()=>window.removeEventListener('popstate',pop)},[]);
const refresh=async()=>{try{const r=await fetch('/api/workspace');if(r.ok){const v=await r.json() as any;setRecords(v);const t=v.find((x:Rec)=>x.kind==='team');if(t)setTeam(t.data.name)}}catch{}};
useEffect(()=>{refresh()},[]);
useEffect(()=>{if(!playing||source)return;const t=setInterval(()=>setTime(t=>{if(t>=5400){setPlaying(false);return 5400}return t+Number(speed.replace('×',''))}),1000);return()=>clearInterval(t)},[playing,speed,source]);
useEffect(()=>{if(video.current){video.current.playbackRate=Number(speed.replace('×',''));if(playing)video.current.play().catch(()=>setPlaying(false));else video.current.pause()}},[playing,speed]);
useEffect(()=>{if(!job||job.step>=7)return;const id=setInterval(async()=>{try{const r=await fetch(`/api/videos?id=${job.id}&status=1`);if(r.ok){const data=await r.json() as any;setJob((j:any)=>({...j,...data}));if(data.step===7){toast.success('Demo processing complete. Your footage is ready to review.');refresh()}}}catch{}},1800);return()=>clearInterval(id)},[job?.id,job?.step]);
const jump=(t:number)=>{setTime(Math.max(0,Math.min(t,source?video.current?.duration||5400:5400)));if(video.current)video.current.currentTime=t};
useEffect(()=>{const mc=(document as any).modelContext;if(!mc?.registerTool)return;const controller=new AbortController();Promise.resolve(mc.registerTool({name:'jump_to_demo_event',description:'Navigate to a seeded match event on the visible timeline.',inputSchema:{type:'object',properties:{eventId:{type:'string'}},required:['eventId'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:any)=>{const e=events.find(e=>e.id===input.eventId);if(!e)throw new Error('Unknown demo event');setSource('');setTime(e.time);setView('match');return {timestamp:e.time,title:e.title}}},{signal:controller.signal})).catch(()=>{});return()=>controller.abort()},[]);
const save=async(kind:string,data:any,id?:string)=>{try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({kind,data,id})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);await refresh();return true}catch(e){toast.error((e as Error).message);return false}};
const review=async(e:any,status:string)=>{if(await save('review',{eventId:e.id,status},e.id))toast.success(status==='accepted'?'Observation accepted':'Review updated')};
const ask=async(q:string)=>{if(!q.trim()||asking)return;setQuestion('');setMessages(m=>[...m,{role:'user',text:q}]);setAsking(true);try{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q})});const d=await r.json() as any;if(!r.ok)throw Error(d.error);setMessages(m=>[...m,{role:'assistant',...d}])}catch{setMessages(m=>[...m,{role:'assistant',text:'Unable to retrieve the sample analysis. Please try again.'}])}setAsking(false)};
const chooseFile=(f?:File)=>{if(!f||loading)return;if(!f.name.toLowerCase().endsWith('.mp4')||!f.size||f.size>100*1024*1024){toast.error('Choose a non-empty MP4 up to 100 MB.');return}const old=uploadSession.current;if(old&&old.file!==f){void uploadRequest('/api/videos?action=abort',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:old.session.id})}).catch(()=>{});uploadSession.current=null;}setFile(f)};
const upload=async()=>{if(!file||loading||!metadata.opponent.trim()||!metadata.consent)return;setLoading(true);setUploadProgress(0);try{const result=await uploadVideo(file,{...metadata,corners,team},setUploadProgress,uploadSession.current?.file===file?uploadSession.current.session:undefined,session=>{uploadSession.current={file,session}});uploadSession.current=null;window.location.assign('/tracking/'+result.id)}catch(e){toast.error((e as Error).message)}finally{setLoading(false)}};
const filtered=events.filter(e=>(filter==='All events'||filter==='Needs review'&&!records.some(r=>r.kind==='review'&&r.data.eventId===e.id)||filter===e.type)&&(e.title+' '+e.body).toLowerCase().includes(search.toLowerCase()));
const current=events.reduce((a,b)=>Math.abs(b.time-time)<Math.abs(a.time-time)?b:a,events[0]);
const eventCard=(e:typeof events[0],compact=false)=>{const status=records.find(r=>r.kind==='review'&&r.data.eventId===e.id)?.data.status;return <article key={e.id} className={'event-card '+(e.id===current.id?'current':'')}><div className={'event-icon '+e.tone}>{e.tone==='green'?<Target size={17}/>:<Flag size={17}/>}</div><div className="event-copy"><div className="row"><span className={'eyebrow '+e.tone}>{e.type}</span><button className="timestamp" onClick={()=>{setSource('');jump(e.time);setView('match')}}>{stamp(e.time)} <Play size={10}/></button></div><h3>{e.title}</h3>{!compact&&<p>{e.body}</p>}<div className="event-meta"><span>{e.confidence}% confidence</span>{status?<span className="green"><Check size={12}/> {status}</span>:<span>Potential observation</span>}</div>{!compact&&<div className="row event-actions"><button onClick={()=>review(e,'accepted')}><Check size={13}/> Useful</button><button onClick={()=>review(e,'dismissed')}>Dismiss</button><button onClick={()=>{jump(e.time);setModal('note')}}><Plus size={13}/> Note</button></div>}</div></article>};
const player=players[selected-1];
return <SidebarProvider style={{'--sidebar-width':'222px'} as React.CSSProperties}><Toaster theme="dark" position="bottom-right"/><Sidebar className="app-sidebar"><SidebarHeader><a href="/" className="brand"><span className="brand-mark"><Activity size={23}/></span>Pitch<span>IQ</span></a><button className="team-picker" onClick={()=>setModal('team')}><span className="club-badge">N<span>★</span></span><span><strong>{team}</strong><small>First team · 2026 season</small></span><ChevronDown size={14}/></button></SidebarHeader><SidebarContent><div className="nav-caption">WORKSPACE</div><SidebarMenu>{[['dashboard','Overview',LayoutDashboard],['match','Match analysis',Video],['players','Players',Users],['season','Season analytics',BarChart3],['clips','Clip library',Clapperboard]].map(([v,label,Icon]:any)=><SidebarMenuItem key={v}><SidebarMenuButton isActive={view===v} onClick={()=>navigate(v)} className="nav-item"><Icon size={18}/><span>{label}</span>{v==='match'&&<span className="nav-count">5</span>}</SidebarMenuButton></SidebarMenuItem>)}<SidebarMenuItem><SidebarMenuButton onClick={openUpload} className="nav-item nav-upload"><Upload size={18}/><span>Upload video</span></SidebarMenuButton></SidebarMenuItem></SidebarMenu><div className="nav-caption season-label">YOUR SEASON</div><div className="season-mini"><span className="season-dot"/>2026 Regional League<small>5 matches analyzed</small></div><div className="sidebar-bottom-card"><Sparkles size={19}/><strong>A second set of eyes.</strong><p>Explore evidence-led coaching with a sample match.</p><span>DEMO WORKSPACE</span></div></SidebarContent><SidebarFooter><button className="plain sidebar-action" onClick={()=>navigate('settings')}><Settings size={17}/> Workspace settings</button><button className="plain sidebar-action" onClick={()=>navigate('about')}><CircleHelp size={17}/> About PitchIQ</button><div className="account"><span className="avatar">AD</span><div><strong>Coach workspace</strong><small>Private · ChatGPT sign-in</small></div></div></SidebarFooter></Sidebar>
<div className="workspace"><header className="topbar"><div className="breadcrumb"><SidebarTrigger/><span>Workspace</span><ChevronRight size={13}/><strong>{view==='match'?'Match analysis':view==='dashboard'?'Overview':view.charAt(0).toUpperCase()+view.slice(1)}</strong></div><div className="top-actions"><span className="demo-label">DEMO DATA</span><button className="button primary top-upload" onClick={openUpload}><Upload size={15}/><span>Upload video</span></button><button className="icon-btn" aria-label="Notifications" onClick={()=>setModal('notifications')}><Bell size={18}/></button><span className="avatar small">AD</span></div></header>
<main className="main">
{view==='match'?<><div className="page-heading"><div><button className="back-link" onClick={()=>navigate('dashboard')}><ArrowLeft size={13}/> All matches</button><h1>Match analysis</h1><p>See the patterns. Find your next advantage.</p></div><div className="heading-actions"><button className="button" onClick={()=>window.print()}><Download size={15}/> Export report</button><button className="button primary" onClick={()=>{setModal('upload');setStep(0)}}><Plus size={16}/> Upload match</button></div></div>
<section className="match-banner"><div className="match-teams"><div className="team-crest">N<span>★</span></div><div><h2>{team}</h2><small>HOME · 4-3-3</small></div><div className="score">2 <span>–</span> 1<small>FULL TIME</small></div><div className="opponent-crest"><Shield size={27}/></div><div><h2>Cedar Valley FC</h2><small>AWAY · 4-2-3-1</small></div></div><div className="match-details"><span>September 20, 2026 <i>•</i> Regional League</span><small><span className="status-dot"/> Sample analysis ready <i>•</i> 90 minutes</small></div></section>
<Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="main-tabs">{['Overview','Tactical','Players','Events','Clips','Notes'].map(t=><TabsTrigger key={t} value={t}>{t}{t==='Events'&&<span className="tab-count">6</span>}</TabsTrigger>)}</TabsList>
{source&&<p className="notice" style={{marginBottom:16}}>You are watching your uploaded footage. The score, metrics, timeline events, and assistant below still describe the separate Cedar Valley sample match; they are not analysis of your upload.</p>}<div className="analysis-grid"><div className="analysis-left"><section className="video-card"><div className="video-top"><span><span className="status-dot"/>{source?'YOUR FOOTAGE · NOT ANALYZED':'TACTICAL REPLAY'}</span><span>{source?'Overlays unavailable':'Demo reconstruction · overhead view'}</span><button className="icon-btn" aria-label="Expand replay" onClick={()=>setModal('replay')}><Expand size={15}/></button></div><div className="pitch-container">{source?<video ref={video} src={source} onTimeUpdate={e=>setTime(e.currentTarget.currentTime)} onEnded={()=>setPlaying(false)} onError={()=>toast.error('Unable to load video. Reopen it from your dashboard.')} playsInline/>:<Pitch time={time} shape={shape} labels={labels} grid={grid} heat={heat} selected={selected} onSelect={setSelected}/>}<div className="replay-tag"><span>{stamp(time)}</span><span>{source?'Uploaded video':time<2700?'1st half · Demo':'2nd half · Demo'}</span></div>{!source&&<div className="pitch-legend"><span><i/> {team}</span><span><i/> Cedar Valley</span></div>}</div><div className="transport"><button aria-label="Back 10 seconds" onClick={()=>jump(time-10)}><SkipBack size={17}/></button><button className="play-button" aria-label={playing?'Pause':'Play'} onClick={()=>setPlaying(!playing)}>{playing?<Pause size={17}/>:<Play size={17}/>}</button><button aria-label="Forward one frame" onClick={()=>jump(time+1/30)}><SkipForward size={17}/></button><span className="time-display">{stamp(time)} <em>/ {source?stamp(video.current?.duration||0):'90:00'}</em></span><Slider aria-label="Playback position" value={[time]} min={0} max={source?video.current?.duration||5400:5400} step={1} onValueChange={v=>jump(v[0])}/><Choice value={speed} onChange={setSpeed} options={['0.5×','1×','1.5×','2×']}/><button aria-label="Create clip" onClick={()=>{setClipStart(stamp(Math.max(0,time-10)));setClipEnd(stamp(time+10));setModal('clip')}}><Clapperboard size={17}/></button></div><div className="overlay-bar"><span><Layers size={14}/> Overlays</span>{[['Team shape',shape,setShape],['Player IDs',labels,setLabels],['Zones',grid,setGrid],['Heatmap',heat,setHeat]].map(([name,on,set]:any)=><button disabled={!!source} key={name} className={on?'active':''} onClick={()=>set(!on)}>{on&&<Check size={11}/>} {name}</button>)}<button className="overlay-settings" onClick={()=>setModal('correction')} aria-label="Correct player identity"><SlidersHorizontal size={15}/></button></div></section>
<section className="timeline-card"><div className="row"><strong>Match timeline</strong><span className="timeline-key"><i className="green-dot"/> Positive play <i className="amber-dot"/> Review moment</span></div><div className="timeline-ruler">{['00:00','15:00','30:00','HT','60:00','75:00','90:00'].map(t=><span key={t}>{t}</span>)}</div><div className="timeline-track"><div className="phase-track"/>{events.map(e=><button key={e.id} title={`${stamp(e.time)} ${e.title}`} aria-label={`Jump to ${e.title}`} onClick={()=>{setSource('');jump(e.time)}} className={'event-marker '+e.tone} style={{left:e.time/5400*100+'%'}}/>)}<div className="playhead" style={{left:Math.min(100,time/5400*100)+'%'}}><span>{stamp(time)}</span></div></div><div className="timeline-bottom"><span>First half</span><span>Second half</span></div></section>
<TabsContent value="Overview"><div className="section-heading"><h2>Behind the result</h2><span>Estimated · full match</span></div><div className="stat-grid">{[['Possession','58','%', '+4% vs. season'],['Final-third entries','32','', '+6 vs. season'],['High regains','9','', '+2 vs. season'],['Team compactness','28.4','m','−2.1 m vs. season']].map(([name,v,unit,trend])=><div className="stat-card" key={name}><span>{name}</span><strong>{v}<small>{unit}</small></strong><em>{trend}</em><svg viewBox="0 0 100 22" aria-hidden="true"><path d="M0 20L10 16L20 18L30 9L40 13L50 8L60 12L70 3L80 8L90 4L100 0" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div>)}</div><div className="section-heading"><h2>Coach review queue <span className="tab-count">{events.filter(e=>!records.some(r=>r.kind==='review'&&r.data.eventId===e.id)).length}</span></h2><button className="text-button" onClick={()=>setTab('Events')}>View all events <ArrowRight size={14}/></button></div><div className="review-grid">{events.slice(2,4).map(e=>eventCard(e))}</div></TabsContent>
<TabsContent value="Tactical"><div className="section-heading"><h2>Team shape & territory</h2><Choice value={filter.startsWith('In ')||filter.startsWith('Out ')?filter:'In possession'} onChange={v=>{setFilter(v);setHeat(v==='In possession');setShape(v!=='In possession')}} options={['In possession','Out of possession']}/></div><div className="panel"><Pitch heat={heat} shape={shape} selected={selected} onSelect={setSelected}/><div className="three-stats"><span>Average width<strong>48.2 m</strong></span><span>Average length<strong>32.1 m</strong></span><span>Defensive line<strong>38.4 m</strong></span></div><p className="muted">Seeded whole-match positions. Phase controls change the visualization; real phase metrics require the tracking service.</p></div><div className="section-heading"><h2>Half-by-half comparison</h2></div><div className="panel comparisons">{[['Team width',45,51],['Final-third entries',14,18],['High regains',4,5]].map(([name,a,b]:any)=><div key={name}><span>{name}</span><strong>{a} <small>1st half</small> / {b} <small>2nd half</small></strong></div>)}</div></TabsContent>
<TabsContent value="Players"><PlayerList/></TabsContent>
<TabsContent value="Events"><div className="section-heading"><h2>Match events</h2><Choice value={filter} onChange={setFilter} options={['All events','Needs review',...events.map(e=>e.type)]}/></div><div className="search-box"><Search size={16}/><input placeholder="Search observations…" value={search} onChange={e=>setSearch(e.target.value)}/></div>{filtered.length?filtered.map(e=>eventCard(e)):<div className="empty">No events match these filters.</div>}</TabsContent>
<TabsContent value="Clips"><Clips/></TabsContent><TabsContent value="Notes"><Notes/></TabsContent></div>
<aside className="insights-panel"><Tabs defaultValue="insights"><TabsList className="side-tabs"><TabsTrigger value="insights"><Sparkles size={15}/> Insights <span>6</span></TabsTrigger><TabsTrigger value="assistant"><MessageSquare size={15}/> Ask PitchIQ</TabsTrigger></TabsList><TabsContent value="insights"><div className="insight-intro"><div className="row"><h2>A closer look</h2><span className="ai-badge">AI DEMO</span></div><p>Potential coaching observations, grounded in sample match evidence.</p></div><div className="insight-list">{events.slice(2).map(e=>eventCard(e))}</div><div className="insight-footer"><Shield size={15}/><p>Your judgment comes first. Review observations before using them with players.</p></div></TabsContent><TabsContent value="assistant"><div className="assistant"><span className="assistant-mark"><Sparkles size={24}/></span><h2>Your film-room assistant</h2><p>Explore the sample match. Every observation leads back to its evidence.</p><span className="muted">Fixture-based responses · no live AI</span>{messages.length===0&&<div className="suggestions">{['What were our biggest defensive issues?','Show our right-side overloads','Who covered the most distance?'].map(q=><button onClick={()=>ask(q)} key={q}>{q}<ArrowUpRight size={13}/></button>)}</div>}<div className="messages" aria-live="polite">{messages.map((m,i)=><div className={'message '+m.role} key={i}><small>{m.role==='user'?'YOU':'PITCHIQ · SAMPLE EVIDENCE'}</small><p>{m.text}</p>{m.events?.map((e:any)=><button key={e.id} className="timestamp" onClick={()=>{setSource('');jump(e.time)}}>{stamp(e.time)} · {e.type}</button>)}</div>)}{asking&&<p>Retrieving sample evidence…</p>}</div><form onSubmit={e=>{e.preventDefault();ask(question)}} className="ask-form"><input aria-label="Ask about the match" placeholder="Ask about this match…" value={question} onChange={e=>setQuestion(e.target.value)} maxLength={2000}/><button aria-label="Send question" disabled={asking}><Send size={17}/></button></form></div></TabsContent></Tabs></aside></div></Tabs></>:
view==='dashboard'?<><PageHeading title="Your coaching overview" text="The whole season. A clear next step."/><div className="welcome-panel"><div><span className="eyebrow green">2026 REGIONAL LEAGUE</span><h2>Good teams review.<br/>Great teams find a pattern.</h2><p>Your latest match is ready for a closer look.</p><button className="button primary" onClick={()=>navigate('match')}>Review latest match <ArrowRight size={16}/></button></div><div className="record-score"><strong>3 <span>1</span> 1</strong><span>WINS <i>DRAWS</i> LOSSES</span></div></div><div className="section-heading"><h2>Match library</h2><span>Seeded demo season</span></div><div className="match-list">{matches.map((m,i)=><button key={m.opponent} className="match-row" onClick={()=>i===0?navigate('match'):toast.info('Detailed analysis is available for the Cedar Valley demo match.')}><span className={'result '+m.result}>{m.result}</span><div><h3>{team} <span>vs</span> {m.opponent}</h3><small>{m.date} · Regional League</small></div><strong>{m.score}</strong><span className="ready">{i===0?'Open analysis':'Season summary'}</span><ChevronRight size={18}/></button>)}</div><div className="section-heading"><h2>Your uploaded footage</h2></div>{records.filter(r=>r.kind==='video').length?records.filter(r=>r.kind==='video').map(r=><div className="match-row" key={r.id}><Video size={24}/><div><h3>{r.data.metadata.opponent}</h3><small>{r.data.filename} · Unanalyzed footage</small></div><button className="button" onClick={()=>window.location.assign('/tracking/'+r.id)}>Label & track</button><button aria-label="Delete video" className="icon-btn" onClick={()=>{setJob({id:r.id});setModal('delete')}}><Trash2 size={16}/></button></div>):<div className="empty"><Upload size={25}/><h3>Your next match starts here.</h3><p>Upload an MP4 excerpt to try the setup workflow.</p><button className="button" onClick={openUpload}>Upload match</button></div>}</>:
view==='players'?<><PageHeading title="The players behind the patterns" text="Movement, involvement, and development. Sample season data."/><PlayerList/></>:
view==='season'?<><PageHeading title="One match is a moment. A season is a story." text="2026 Regional League · Seeded demo analytics"/><div className="stat-grid season-stats">{[['Matches','5'],['Win rate','60%'],['Goals for / against','8 / 3'],['Avg. possession','55.8%']].map(([label,n])=><div className="stat-card" key={label}><span>{label}</span><strong>{n}</strong></div>)}</div><div className="two-columns"><section className="panel"><div className="section-heading"><h2>Possession by match</h2><span>Estimate %</span></div><div className="bar-chart">{[...matches].reverse().map(m=><div key={m.opponent}><strong>{m.possession}%</strong><div style={{height:m.possession*2.5}}/><span>{m.date.slice(0,6)}</span></div>)}</div></section><section className="panel"><h2>Recurring coaching focus</h2><div className="focus-item"><span>01</span><div><h3>Protect the space between lines</h3><p>Review midfield-to-defense spacing at 42:18.</p><button className="text-button" onClick={()=>{navigate('match');jump(2538)}}>Review evidence <ArrowRight size={14}/></button></div></div><div className="focus-item"><span>02</span><div><h3>Keep the width on the right</h3><p>A positive pattern to repeat in training.</p></div></div><p className="muted">Suggested focus from the demo match. Recurrence across games has not been measured.</p></section></div><div className="section-heading"><h2>Results over time</h2></div>{matches.map(m=><div className="match-row" key={m.opponent}><span className={'result '+m.result}>{m.result}</span><h3>{m.opponent}</h3><small>{m.date}</small><strong>{m.score}</strong></div>)}</>:
view==='clips'?<><PageHeading title="Your film room" text="Saved timestamp ranges for the next team session."/><Clips/></>:
view==='settings'?<><PageHeading title="Workspace settings" text="Your team, your footage, your decisions."/><section className="panel settings-panel"><h2>Team workspace</h2><p>{team} · Private owner workspace</p><button className="button" onClick={()=>setModal('team')}>Edit team</button><h2>Privacy & retention</h2><p>Uploaded videos are private to your signed-in account. You can delete footage from the overview. Automatic retention and team invitations are not enabled in this MVP.</p><h2>Roles</h2><p>Head coach (owner) is active. Assistant coach, analyst, and player access are planned.</p><h2>Account</h2><a className="button" href="/signin-with-chatgpt?return_to=/settings" target="_top">Sign in with ChatGPT</a><h2>Analysis transparency</h2><p>Season statistics and tactical findings are seeded demo data. Uploaded matches have a separate labeling workspace with experimental short-clip appearance tracking. No uploaded footage is used to train models.</p></section></>:
<><div className="landing"><span className="eyebrow green">THE COACHING ADVANTAGE</span><h1>Turn game film into<br/><em>coaching decisions.</em></h1><p>One workspace for your footage, your team's patterns, and the moments that matter.</p><button className="button primary" onClick={()=>navigate('match')}>Explore the demo <ArrowRight size={17}/></button><div className="landing-pitch"><Pitch shape/></div></div><div className="three-stats feature-cards">{[['01','Bring your game','Upload overhead MP4 footage and set up your team.'],['02','Find the patterns','Explore movement, shape, and timestamped observations.'],['03','Coach with context','Review the evidence and turn insights into your next session.']].map(([n,t,b])=><div key={n}><span>{n}</span><h2>{t}</h2><p>{b}</p></div>)}</div><section className="panel"><h2>Built for the film room</h2><p>PitchIQ is currently a demo MVP. Pricing and team plans will be announced when production video analysis is available.</p></section></>}
<footer className="page-footer"><span>PitchIQ <i>·</i> A clearer view of the game.</span><span>Sample data. Coach-reviewed decisions.</span></footer></main></div>
<Dialog open={!!modal} onOpenChange={open=>!open&&setModal('')}><DialogContent className={modal==='upload'||modal==='replay'?'wide-modal':''}><DialogHeader><DialogTitle>{{upload:'Set up your next match',note:'Add a coaching note',clip:'Save a clip range',team:'Your team workspace',correction:'Correct player identity',notifications:'Notifications',delete:'Delete uploaded video?',replay:'Tactical replay'}[modal]}</DialogTitle><DialogDescription>{modal==='upload'?'MP4 excerpt · Up to 100 MB · Mock analysis pipeline':modal==='replay'?'Simulated positions, not real match footage.':'Private to your coaching workspace.'}</DialogDescription></DialogHeader>
{modal==='replay'&&<Pitch time={time} shape={shape} labels={labels} selected={selected} onSelect={setSelected}/>}
{modal==='team'&&<><label>Team name<input value={teamDraft} placeholder={team} onChange={e=>setTeamDraft(e.target.value)}/></label><button className="button primary" onClick={async()=>{if(teamDraft.trim()&&await save('team',{name:teamDraft.trim()},'team')){setTeam(teamDraft);setModal('')}}}>Save team</button></>}
{modal==='note'&&<><span className="timestamp">{stamp(time)} · {source?'Uploaded footage':'Cedar Valley demo match'}</span><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="What should the team take from this moment?" rows={5}/><button className="button primary" disabled={!note.trim()} onClick={async()=>{if(await save('note',{text:note,time,source:source||'demo'})){setNote('');setModal('');toast.success('Coaching note saved')}}}>Save note</button></>}
{modal==='clip'&&<><p>Save a timestamp bookmark. Video rendering and downloadable clip exports are planned.</p><div className="two-columns"><label>Start (mm:ss)<input value={clipStart} onChange={e=>setClipStart(e.target.value)}/></label><label>End (mm:ss)<input value={clipEnd} onChange={e=>setClipEnd(e.target.value)}/></label></div><button className="button primary" onClick={async()=>{const parse=(s:string)=>/^\d{1,3}:[0-5]\d$/.test(s)?s.split(':').reduce((a,v)=>a*60+Number(v),0):NaN;const a=parse(clipStart),b=parse(clipEnd);if(!Number.isFinite(a)||!Number.isFinite(b)||b<=a||b>(source?video.current?.duration||5400:5400)){toast.error('Enter valid times, with the end after the start and within the video.');return}if(await save('clip',{start:a,end:b,title:`Review at ${clipStart}`,source:source||'demo'})){setModal('');toast.success('Clip range saved')}}}>Save to clip library</button></>}
{modal==='correction'&&<><p>Select the demo track and assign a roster identity. Corrections are saved for review; they do not retrain a model.</p><Choice value={String(selected)} onChange={v=>setSelected(Number(v))} options={players.map(p=>String(p.id))}/><label>Roster identity<input value={teamDraft} placeholder={player.name} onChange={e=>setTeamDraft(e.target.value)}/></label><button className="button primary" onClick={async()=>{if(!teamDraft.trim())return;if(await save('player',{track:selected,name:teamDraft,time},'track-'+selected)){setModal('');toast.success('Identity correction saved')}}}>Save correction</button></>}
{modal==='notifications'&&<div className="panel"><Check className="green"/><h3>Sample match ready</h3><p>{team} vs Cedar Valley FC is ready to explore.</p>{job?.step===7&&<p>Your uploaded footage is ready for manual review. Demo processing is complete.</p>}</div>}
{modal==='delete'&&<><p>This permanently deletes the uploaded video. Saved notes and clip bookmarks are retained.</p><button className="button danger" onClick={async()=>{const r=await fetch('/api/videos',{method:'DELETE',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:job.id})});if(r.ok){setModal('');refresh();toast.success('Video deleted')}else toast.error('Unable to delete video. Please retry.')}}>Delete video</button></>}
{modal==='upload'&&<><p>Upload a short clip, then label the players directly on your video. Existing uploads can be opened from Overview.</p><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();chooseFile(e.dataTransfer.files[0])}}><Upload size={30}/><strong>{file?file.name:'Drop your match footage here'}</strong><p>MP4 · up to 100 MB · start with a 30–60 second excerpt</p><button className="button" disabled={loading} onClick={()=>fileInput.current?.click()}>Choose video</button><input ref={fileInput} type="file" accept="video/mp4,.mp4" hidden onChange={e=>chooseFile(e.target.files?.[0])}/></div><div className="two-columns"><label>Opponent<input value={metadata.opponent} onChange={e=>setMetadata({...metadata,opponent:e.target.value})} placeholder="Opponent name"/></label><label>Match date<input type="date" value={metadata.date} onChange={e=>setMetadata({...metadata,date:e.target.value})}/></label></div><p className="notice">Your match opens in its own labeling workspace. Tracking is an experimental short-clip tool; tactical statistics are not generated.</p><label className="switch-row"><Switch checked={metadata.consent} onCheckedChange={v=>setMetadata({...metadata,consent:v})}/> I have permission to upload this footage, including consent for youth players where required.</label>{loading&&<><Progress value={uploadProgress}/><small>{uploadProgress>=99?'Finishing and verifying your video…':`Uploading ${uploadProgress}%`}</small></>}<button className="button primary" disabled={!file||!metadata.opponent.trim()||!metadata.consent||loading} onClick={upload}>{loading?(uploadProgress>=99?'Finishing…':'Uploading…'):'Upload & label players'}</button></>}
</DialogContent></Dialog></SidebarProvider>;
function PageHeading({title,text}:{title:string,text:string}){return <div className="page-heading"><div><span className="eyebrow green">{team} / 2026</span><h1>{title}</h1><p>{text}</p></div><button className="button primary" onClick={openUpload}><Plus size={16}/> Upload match</button></div>}
function Notes(){return <><div className="section-heading"><h2>Coaching notes</h2><button className="button" onClick={()=>setModal('note')}><Plus size={15}/> Add note</button></div>{records.filter(r=>r.kind==='note').length?records.filter(r=>r.kind==='note').map(r=><div className="panel saved-note" key={r.id}><button className="timestamp" onClick={()=>{setSource(r.data.source==='demo'?'':r.data.source);jump(r.data.time)}}>{stamp(r.data.time)}</button><p>{r.data.text}</p></div>):<div className="empty"><MessageSquare size={26}/><h3>Make the observation yours.</h3><p>Add a timestamped note while reviewing the match.</p></div>}</>}
function Clips(){return <><div className="section-heading"><h2>Saved clip ranges</h2><button className="button" onClick={()=>setModal('clip')}><Plus size={15}/> Create clip range</button></div>{records.filter(r=>r.kind==='clip').length?records.filter(r=>r.kind==='clip').map(r=><div className="match-row" key={r.id}><Clapperboard size={24}/><div><h3>{r.data.title}</h3><small>{stamp(r.data.start)} – {stamp(r.data.end)} · Timestamp bookmark</small></div><button className="button" onClick={()=>{navigate('match');setSource(r.data.source==='demo'?'':r.data.source);jump(r.data.start)}}><Play size={14}/> Open</button></div>):<div className="empty"><Clapperboard size={28}/><h3>Keep the moments that matter.</h3><p>Save a range from the timeline for your next film session.</p></div>}<p className="muted">Clip downloads and permissioned sharing are planned. Saved ranges open the original footage.</p></>}
function PlayerList(){return <><div className="section-heading"><h2>Player performance</h2><span>90 min · Sample estimates</span></div><div className="player-layout"><div className="panel player-table"><Table><TableHeader><TableRow><TableHead>Player</TableHead><TableHead>Role</TableHead><TableHead>Distance</TableHead></TableRow></TableHeader><TableBody>{players.map(p=><TableRow key={p.id} className={selected===p.id?'selected-row':''} onClick={()=>setSelected(p.id)}><TableCell><button className="player-name" onClick={()=>setSelected(p.id)}><span>{p.number}</span>{records.find(r=>r.kind==='player'&&r.data.track===p.id)?.data.name||p.name}</button></TableCell><TableCell>{p.position}</TableCell><TableCell>{p.distance} km</TableCell></TableRow>)}</TableBody></Table></div><div className="panel player-profile"><span className="jersey">{player.number}</span><h2>{player.name}</h2><p>{player.position} · 90 minutes played</p><Pitch heat shape={false} selected={selected} onSelect={setSelected}/><div className="three-stats"><span>Distance<strong>{player.distance} km</strong></span><span>Minutes<strong>90</strong></span></div><p className="muted">Illustrative heatmap. Workload is a sample estimate, not medical guidance.</p><button className="button" onClick={()=>setModal('note')}>Add development note</button></div></div></>}
}
