import {identity,db,bucket,failure} from '@/lib/server';
import {initialTracking,trackingSchema,pointSchema,fieldCameraSchema} from '@/lib/tracking';
import {z} from 'zod';
import {observationSchema,reidEventSchema} from '@/lib/soccer-schema';
const input=z.object({videoId:z.string().uuid(),revision:z.number().int().min(0),document:trackingSchema,archive:z.object({id:z.string().uuid(),points:z.array(pointSchema).max(6000),observations:z.array(observationSchema).max(4000),events:z.array(reidEventSchema).max(200).optional(),fieldCamera:z.array(fieldCameraSchema).max(1800)}).optional()});
async function owned(videoId:string,owner:string){return db().prepare('SELECT data FROM records WHERE id=? AND owner=? AND kind=?').bind(videoId,owner,'video').first<{data:string}>();}
export async function GET(request:Request){try{const owner=await identity();const videoId=new URL(request.url).searchParams.get('videoId')||'';const video=await owned(videoId,owner);if(!video)return Response.json({error:'Match not found.'},{status:404});const meta=JSON.parse(video.data);const row=await db().prepare('SELECT data FROM records WHERE id=? AND owner=? AND kind=?').bind(owner+':tracking:'+videoId,owner,'tracking').first<{data:string}>();return Response.json({video:{id:videoId,filename:meta.filename,metadata:meta.metadata},...(row?JSON.parse(row.data):{revision:0,document:initialTracking(meta.metadata?.team||'Team A',meta.metadata?.opponent||'Team B')})},{headers:{'Cache-Control':'private, no-store'}});}catch(e){return failure(e);}}
export async function POST(request:Request){try{const owner=await identity();if(Number(request.headers.get('content-length'))>2500000)return Response.json({error:'Tracking checkpoint is too large. Use a smaller checkpoint interval.'},{status:413});const raw=await request.text();if(raw.length>2500000)return Response.json({error:'Tracking data is too large.'},{status:413});let parsed;try{parsed=input.safeParse(JSON.parse(raw));}catch{return Response.json({error:'Invalid request.'},{status:400});}if(!parsed.success)return Response.json({error:parsed.error.issues[0]?.message||'Invalid tracking data.'},{status:400});const {videoId,revision,document,archive}=parsed.data;if(!await owned(videoId,owner))return Response.json({error:'Match not found.'},{status:404});const next=revision+1;const data=JSON.stringify({revision:next,document});const id=owner+':tracking:'+videoId;
let archiveKey:string|undefined;
if(archive){
 if(!document.historySegments?.some(s=>s.id===archive.id))return Response.json({error:'History manifest is missing this checkpoint.'},{status:400});
 if(archive.points.some(p=>!document.players.some(player=>player.id===p.playerId)))return Response.json({error:'Unknown archived player.'},{status:400});
 archiveKey=owner+'/tracking/'+videoId+'/'+archive.id+'.json';
 // Immutable object names prevent a losing revision from rewriting committed history.
 if(await bucket().head(archiveKey))return Response.json({error:'History checkpoint already exists. Reload the saved checkpoint.'},{status:409});
 await bucket().put(archiveKey,JSON.stringify(archive),{httpMetadata:{contentType:'application/json'}});
}
const result=revision===0?await db().prepare('INSERT OR IGNORE INTO records (id,owner,kind,data,created) VALUES (?,?,?,?,?)').bind(id,owner,'tracking',data,Date.now()).run():await db().prepare("UPDATE records SET data=? WHERE id=? AND owner=? AND kind='tracking' AND json_extract(data,'$.revision')=?").bind(data,id,owner,revision).run();if(!result.meta.changes){if(archiveKey)await bucket().delete(archiveKey);return Response.json({error:'This match was changed in another tab. Your edits are still on screen. Reload to get the latest saved version.'},{status:409});}return Response.json({revision:next});}catch(e){return failure(e);}}
